### PR TITLE
Replace vendored YarnSpinner.Compiler code with YarnSpinner.Compiler package

### PR DESCRIPTION
**Pull request by desplesda**
Starting with v2.0.0-beta6, YarnSpinner.Compiler is [now available as a package on NuGet](https://www.nuget.org/packages/YarnSpinner.Compiler/2.0.0-beta0006). This PR removes the code that had been copied from [the main Yarn Spinner repo](https://github.com/YarnSpinnerTool/YarnSpinner), and replaces it with a package reference to YarnSpinner.Compiler in YarnLanguageServer.csproj.

- desplesda/YarnSpinnerLanguageServer@a9dada7 removes the previous code;
- desplesda/YarnSpinnerLanguageServer@07fbddc updates the rest of the codebase to use the package's APIs.

As part of this change, a few alterations had to be made to bring the language server in line with the upstream Yarn Spinner parser:

- `jump_destination` was renamed to `jump_statement`; the completion handler, references visitor, and semantic token visitor have been updated.
- `function_name` has been replaced with a reference to the `function_call` rule's `FUNC_ID` token.
- (The most significant change): The command parameter code has been replaced, and now uses a new class `CommandTextSplitter` to break the text of a command into syntactically discrete chunks (just like the Unity implementation does).

This last point needs a bit of input from others who have been reading this code more than I have; I don't think I entirely understand how the parameter range logic is meant to work, and I'm seeing that warnings for unknown commands that should be associated with the command's use are actually being displayed at the very start of the file:

image

image

Other than this issue, I hope that this is useful, and will help prevent potential drift between the compiler in this project and the upstream compiler.

### CODE REVIEW

**Comment by desplesda** [comment]
(I think that this issue is caused by me not quite replicating the existing behaviour that was present in `ReferencesVisitor.VisitCommand_statement`.)

**Comment by desplesda** [comment]
Hello! Following up on this. Is there anything additional you’d like me to do on this in order to make this ready for merge?

**Comment by pappleby** [comment]
Hey @desplesda! Apologies for the radio silence, this month has been unexpectedly busy. I have a couple small fixes, but I'll apply them after the merge. Thanks again for putting this together!

**Comment by pappleby** [comment]
The fix for errors all being at the beginning of the file was just to giving more position information to the Token constructor in the ReferencesVisitor / SemanticTokenVisitor.

**Pull request merged**
